### ISSUE TITLE
Agregar nuevos miembros de staff y actualizar fotos de comunidad 

### ISSUE THREAD

**Issue by tatymoly** [Noders/Noders.com#100]
Holi ❤️  Ahora somos más, creo que sería bonito agregar a los miembros más activos en la sección de comunidad. Si es muy difícil ignoren este issue (?) 😄

**Comment by fforres** [comment]
Necesitamos una idea de diseño nueva... nos vemos mucho mas grandes/importantes que la gente. 

Si ponemos al todo el team al final? tb con hexagonos?

**Comment by fforres** [comment]
Hay algo que quiero hacer hace como un año, que es ponerle un overlay (con el username(?) )cuando pasas el mouse/haces tap/haces click por arriba de las fotos.

Muy auto-referente... algo como esto, pero hexagonal https://segment.com/team

**Comment by tatymoly** [comment]
Me tinca sacar la sección del staff, después de todo siempre cambia. También traté de alinear los exagonos intruseando en el css pero no pude xD ! onda para que queden como panal de abejas. Me gusta lo que dice  Felipe de poner los username sobre cada foto. Y me gusta mucho lo de las secciones. Estamos trabajando para lograr tener las charlas mensuales de meetups en youtube, así que quizás podríamos poner un section en donde se muestre el ultimo video de youtube agregado. 

Además,  creo que faltan fotitos :) digo, si le muestro a un posible Sponsor el sitio, me gustaría ver fotos de los eventos ahí mismo en la web. Veamos todo eso? :D

**Comment by Xabadu** [comment]
@tatymoly tienes algun mockup/propuesta de que agregar o cambiar? Seria bueno para darle una vuelta. Si quieres con eso podemos hacer pairing y trabajar en esos cambios ;)

**Comment by tatymoly** [comment]
@Xabadu  yap, déjame pensar en alguna propuesta y se las mando :) (está difícil porque me gusta la página y tiene una identidad propia)

**Comment by Xabadu** [comment]
@tatymoly esto se resuelve con tu PR? Para ver si cerramos el issue o lo mantenemos abierto.

**Comment by tatymoly** [comment]
@Xabadu  Sip! Resuelto. Thanks :)
