### ISSUE TITLE
BUG - Hero no del 100vh en IOS

### ISSUE THREAD

**Issue by fforres** [Noders/Noders.com#102]
El hero deja ver el background de la app
![image uploaded from ios](https://user-images.githubusercontent.com/952992/36769099-09cf1542-1bf7-11e8-96f1-7835b15bbd16.png)

**Comment by tatymoly** [comment]
Se puede arreglar creando una clase con `margin-top: -5%` y agregándola a los section (o los divs en donde se vea espacio), pero si quieres hago yo eso apenas tenga un ratito

**Comment by fforres** [comment]
Closing! :D
