### ISSUE TITLE
Twitter de Caro

### ISSUE THREAD

**Issue by enBonnet** [Noders/Noders.com#108]
Ya que @carolina-pinzon no utiliza su twitter sería mejor colocar un link a su github ¿Que les parece?

XoXo

**Comment by tatymoly** [comment]
Buen punto. Lo voy a agregar a una lista de mejoras que tengo para hacer el cambio. ❤️  Gracias @enBonnet  :)

**Comment by Xabadu** [comment]
o puedes mandar un PR si quieres tb @enBonnet :D

**Comment by tatymoly** [comment]
@enBonnet esto está listo? :) para cerrarlo

**Comment by Xabadu** [comment]
No, hay un PR abierto con esto #109

**Comment by tatymoly** [comment]
Ah! Oka, no me había fijado.

**Comment by enBonnet** [comment]
Update on PR #109
