### ISSUE TITLE
Agregar Prettier

### ISSUE THREAD

**Issue by fforres** [Noders/Noders.com#113]
La idea -> 
- Agregar prettier para que auto-formatee el codigo
	- https://github.com/prettier/prettier
- Agregar eslint-prettier config para que no haga conflictos con el lint actual :P 
- Agregar Husky para que con cada commit arregle el codigo
	- https://github.com/typicode/husky

**Comment by fforres** [comment]
@tatymoly Cualquier consulta, dime :) 

La idea es que:
1. Al usar prettier, no cause conflictos con eslint
2. Al hacer un commit, husky ejecute 'prettier' y 'eslint --fix', creo que en el repo de husky hay un par de ejemplos

**Comment by tatymoly** [comment]
Oki doki

**Comment by Xabadu** [comment]
Fixed in #120
