### ISSUE TITLE
Nombre de usuario de Taty

### ISSUE THREAD

**Issue by enBonnet** [Noders/Noders.com#114]
Cuando el ancho de la página es inferior `765` como en este ejemplo:

![captura de pantalla 2018-03-23 21 31 37](https://user-images.githubusercontent.com/13243693/37858310-e6d3df3e-2ee1-11e8-8e50-5c86f6fe3215.png)

El nombre de usuario de @tatymoly pierde la linea y se ve un poco mas abajo.

![captura de pantalla 2018-03-23 21 27 38](https://user-images.githubusercontent.com/13243693/37858325-107c542e-2ee2-11e8-8543-ed44194ae2a9.png)

En la foto se puede comprar con el de nicoavila

**Comment by tatymoly** [comment]
Mi foto no carga en los hexagonos, mi nombre se baja, damn it 😢  haha. Le echaré un ojo :)

**Comment by tatymoly** [comment]
btw @enBonnet  como pusiste esas lineas? :o

**Comment by enBonnet** [comment]
Firefox ❤️

**Comment by Xabadu** [comment]
Fixed in #119
