### ISSUE TITLE
Error de carga sin www

### ISSUE THREAD

**Issue by juandav** [Noders/Noders.com#130]
Cuando deseo ingresar a noders sin www "[noders](https://noders.com/)", aparece el siguiente error:

 
![image](https://user-images.githubusercontent.com/12274145/64959656-3a194600-d857-11e9-9de4-4a677a18506b.png)

**Comment by fforres** [comment]
Uff! tuvimos un problema con el DNS :)
Pero ya esta todo arriba :D

Graciuas por el headsup master!
*Felipe Andrés Torres Sepúlveda*
*noders.com <http://www.noders.com> - fforr.es <http://fforr.es>*

**Comment by fforres** [comment]
Por si quieres darle una revisada al PR que lo arregla :p 
https://github.com/Noders/Noders.com/issues/130

**Comment by juandav** [comment]
:thumbsup: gracias. :wink:
