### ISSUE TITLE
Arreglar SVGs en Mobile

### ISSUE THREAD

**Issue by fforres** [Noders/Noders.com#46]
Los SVG no se visualizan en chrome mobile / safari

**Comment by fforres** [comment]
Son varias imágenes.
Habría que hacer un test para ver cuantos KB son.
 Podríamos no cargarlos en mobile? Cargarlos on-request? O tener una solución distinta para mobile que para desktop?

No quiero destruir el plan de datos de alguien 😂

**Comment by Xabadu** [comment]
Creo que deberiamos optar por algo distinto para esa seccion en mobile, igual es n contenido y no se si es la mejor forma de mostrarlo.

**Comment by fforres** [comment]
Por si queremos probarlo en mobile, acá hay algo de info de como hacer funcionar sgv patterns 
https://stackoverflow.com/questions/20459685/how-do-i-use-svg-patterns-in-a-cross-browser-consistent-way
