### ISSUE TITLE
Cambiar logos de media por version blanca de Noders

### ISSUE THREAD

**Issue by Xabadu** [Noders/Noders.com#53]

**Comment by Xabadu** [comment]
@fforres tienes los editables de esos logos?

**Comment by Xabadu** [comment]
@fforres ^^

**Comment by fforres** [comment]
Pense q te lo habia mandado por internorss
acá estan -> https://drive.google.com/open?id=0B0-c8vrue2QqfmVya2dNejRMTy1fM29lUG9GamFfSmQtNXdVblh5Yjl1MVJvOUVRV1JuUkE

**Comment by tatymoly** [comment]
Esto está hecho :P
