### ISSUE TITLE
Doble scroll

### ISSUE THREAD

**Issue by devrchancay** [Noders/Noders.com#67]
No se si esa sea la idea pero el nav cubre casi todo el scroll, lo que hace complicado "scrollear" :grinning: 

![image](https://user-images.githubusercontent.com/4138285/28632978-d59481ee-71f7-11e7-9156-336af32d56e3.png)

¿Esa era la idea de diseño?, Yo puedo solucionar eso dejando solo el scroll del browser

**Comment by Xabadu** [comment]
@devrchancay no, no es intencional. Yo al menos no lo note antes. Un PR seria maravilloso 🤘
